// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCeN9iFwCBD7fH9evhIQrpcPlssW3R5fDE',
    appId: '1:431535707736:web:bf1bba1923152fc077dc2d',
    messagingSenderId: '431535707736',
    projectId: 'maidmatch-4c8e2',
    authDomain: 'maidmatch-4c8e2.firebaseapp.com',
    storageBucket: 'maidmatch-4c8e2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWQak7sUWJX3q9NYTjA9DHdzhVLqoVyGM',
    appId: '1:431535707736:android:438321957303386c77dc2d',
    messagingSenderId: '431535707736',
    projectId: 'maidmatch-4c8e2',
    storageBucket: 'maidmatch-4c8e2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyrX3xwE_RqkEZ8d_PJhUGqVmgrrGBVXc',
    appId: '1:431535707736:ios:bdac5a9352fc055877dc2d',
    messagingSenderId: '431535707736',
    projectId: 'maidmatch-4c8e2',
    storageBucket: 'maidmatch-4c8e2.appspot.com',
    androidClientId: '431535707736-3oqe8p3tiea0mb855c1djevjiefvge7a.apps.googleusercontent.com',
    iosClientId: '431535707736-qdbcicnvm949qkatvvohb0979e2eulis.apps.googleusercontent.com',
    iosBundleId: 'com.example.maidsmatchMaids',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyrX3xwE_RqkEZ8d_PJhUGqVmgrrGBVXc',
    appId: '1:431535707736:ios:0acb22e7f2a8a74477dc2d',
    messagingSenderId: '431535707736',
    projectId: 'maidmatch-4c8e2',
    storageBucket: 'maidmatch-4c8e2.appspot.com',
    androidClientId: '431535707736-3oqe8p3tiea0mb855c1djevjiefvge7a.apps.googleusercontent.com',
    iosClientId: '431535707736-6u5nvs4s7n8ef9varec1ei0g17qgskrb.apps.googleusercontent.com',
    iosBundleId: 'com.example.maidsmatchMaids.RunnerTests',
  );
}
